### ISSUE TITLE
Docker build downloads videos to unknown location

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#44]
Hi 

I am trying to to use the Docker build, it seems to work but I cant figure out where it is downloading the file. 

It is definetely not downloading them to "data/videos" It sure downloads them, I see them in the Ui.

Here is the relevant yaml File

```
version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./app/YtManagerApp/static:/www/static
      - /media/O/MEDIA/YTSM_MEDIA:/www/media
    ports:
      - "8001:80"
    depends_on:
      - web

  web:
    build: .
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - /opt/ytsm/config:/usr/src/ytsm/config
      - /media/O/MEDIA/YTSM_MEDIA/data:/usr/src/ytsm/data

```

So where is the downloaded files?
